
package cours


import droolscours.Account;
import droolscours.AccountingPeriod;
import droolscours.CashFlow;
import droolscours.util.OutputDisplay;

global OutputDisplay showResults;

rule "Credit rule 2a"

   	when
   		$cash :CashFlow( $aDate : mvtDate, $no : accountNo ,type == CashFlow.CREDIT )
   		$acc : Account(accountno ==$no  )
   	then
   		$acc.setBalance($acc.getBalance()+$cash.getAmount());
   		showResults.showText("Account no "+$acc.getAccountno()+ " has now a balance of "+$acc.getBalance());
   end
rule "Debit rule 2b"

	when
		$cash :CashFlow( $aDate : mvtDate, $no : accountNo ,type == CashFlow.DEBIT )
		$acc : Account(accountno ==$no  )
	then
		$acc.setBalance($acc.getBalance()-$cash.getAmount());
		showResults.showText("Account no "+$acc.getAccountno()+ " has now a balance of "+$acc.getBalance());
end

