//#created on: 30 oct. 2010
package cours

//#list any import classes here.
import droolscours.Account;
import droolscours.AccountingPeriod;
import droolscours.CashFlow;
import droolscours.util.OutputDisplay;

//#declare any global variables here


global OutputDisplay showResult;


rule "Account group1 4"
	ruleflow-group "Group1"
	when
		Account(  )
	then 
		showResult.showText("Account in Group1");
		
end
rule "Account group2 4"
	ruleflow-group "Group2"
	when
		Account(  )
	then 
		showResult.showText("Account in Group2");
		
end

