//#created on: 30 oct. 2010
package cours

//list any import classes here.
import droolscours.Account;
import util.OutputDisplay;

//#declare any global variables here


global OutputDisplay result;


rule "Your First Rule revisited"
	
	when
		Account(  )
	then 
		result.showText("Le compte existe donc déjà");
		
end

rule "Your Second Rule"
	//#include attributes such as "salience" here...
	when
		//#conditions
	then 
		//#actions
		
end
