//#created on: 30 oct. 2010
package cours

//#list any import classes here.
import droolscours.Account;
import droolscours.AccountingPeriod;
import droolscours.CashFlow;
import droolscours.PrivateAccount;
import droolscours.Customer;
import util.OutputDisplay;
//#declare any global variables here
global OutputDisplay result;


rule "ForAll"
	when
		$acc : Account()
		forall (   Account( this==$acc, $no : accountno  )
					CashFlow( accountNo  == $no)
				   )
	then
		result.showText("All mouvements concerns account no " + $acc.getAccountno());
end
