//#created on: 30 oct. 2010
package lesson4a

//#list any import classes here.
import droolscours.Account;
import droolscours.AccountingPeriod;
import droolscours.CashFlow;
import droolscours.util.OutputDisplay;

//#declare any global variables here


global OutputDisplay showResult;

rule "start process"
	when
	then
		kcontext.getKieRuntime().startProcess("RF3");
end

rule "Account group1 4a"
	ruleflow-group "Group1"
	when
		Account(balance > 0  )
	then 
		showResult.showText("Account in Group1 > 1000 ");
		
end
rule "Account group2 4a"
	ruleflow-group "Group2"
	when
		Account(  )
	then 
		showResult.showText("Account in Group2 < 1000");
		
end

