//#created on: 21 nov. 2010
package loyalty



import util.MyDate;
import loyalty.domains.Ticket;
import loyalty.domains.TicketLine;
import loyalty.domains.Ligneop;
import loyalty.domains.Product
import util.DateHelper;
dialect "mvel"

rule "createdateOpPampers"
	when
	then
	   MyDate t = new MyDate();
	   t.setUneDate1(DateHelper.getDate("2010-12-01"));
	   t.setUneDate2(DateHelper.getDate("2014-12-31"));
	   t.setUneOp("pampers");
	   insert(t);
end
rule "opPameprs"
	when
		MyDate(uneOp=="pampers",$d1:uneDate1,$d2:uneDate2)
		$p : Product( name=="pampers")
		$l : TicketLine(product==$p)
		$t : Ticket(ticketLines contains $l,dateTicket >= $d1 && dateTicket <= $d2)

	then
		$l.setOp(new Ligneop());
		$l.getOp().setMontantReduction(new Float($l.getLineTotal()*0.2));
		$l.getOp().setNomOP("opPameprs");
end

