//#created on: 30 oct. 2010
package cours

//#list any import classes here.
import droolscours.Account;
import droolscours.AccountingPeriod;
import droolscours.CashFlow;
import droolscours.PrivateAccount;
import droolscours.Customer;
import droolscours.util.OutputDisplay;
//#declare any global variables here
global OutputDisplay showResult;

rule "The cashFlow can be a  credit or a debit"

	when
		$cash :CashFlow(type in ( CashFlow.DEBIT,CashFlow.CREDIT) )

	then
		showResult.showText("The cashFlow is a credit or a debit");
end


rule "Accessor"

	when
		$cash :PrivateAccount( owner.name =="Héron" )

	then
		showResult.showText("Account is owned by Héron");
end
rule "infixAnd"
	when
	  ( $c1 : Customer ( country=="GB") and  PrivateAccount(  owner==$c1))
		    or
       ( $c1 : Customer (country=="US") and PrivateAccount(  owner==$c1))


	then
		showResult.showText("Person lives in GB or US");
end
rule "no customer"
	when
		not Customer(  )
	then
		showResult.showText("No customer");
end
rule "Exists"
	when
		exists Account(  )
	then
		showResult.showText("Account exists");
end
rule "ForAll"
	when
		forall (   Account( $no : accountno  )
					CashFlow( accountNo  == $no)
				   )
	then
		showResult.showText("All cashflows are related to an Account ");
end